#!/bin/bash
# Usage: ./rocgist path/to/execute.roc [path/to/additional/file...]

# Install to user bin with:
#   just install-rocgist
# Then use rocgist instead of roc for automatic gist creation

ROC_FILE="$1"
shift  # Remove first arg, leaving additional files in $@
STDOUT="STDOUT.txt"
STDERR="STDERR.txt"
DATE="$(date)"

# Prepend timestamp to output files
echo "# Run at $DATE" > "$STDOUT"
echo "# Run at $DATE" > "$STDERR"

# Run script and append output
roc "$ROC_FILE" >> "$STDOUT" 2>> "$STDERR"

# Upload to gist with additional files if provided
gh gist create "$ROC_FILE" "$STDOUT" "$STDERR" $@ -d "roc $ROC_FILE on $DATE"

echo Gist created with $ROC_FILE $STDOUT $STDERR $@
